language: ruby
sudo: required
dist: trusty
group: edge # https://github.com/travis-ci/travis-ci/issues/5448
services:
  - docker
before_install: gem update --system --no-doc # https://github.com/sickill/rainbow/issues/49
rvm: 2.4.1
matrix:
  exclude:
    - rvm: 2.4.1
  include:
    - rvm: ruby-head
      env: BUNDLE_WITHOUT=test
    - rvm: 2.2.7
      env: BUNDLE_WITHOUT=test
    - rvm: 2.3.4
      env: BUNDLE_WITHOUT=test
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=binary KITCHEN_VARIANT=core
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=source KITCHEN_VARIANT=core
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=binary KITCHEN_VARIANT=unlimited
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=source KITCHEN_VARIANT=unlimited
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=binary KITCHEN_VARIANT=classic
    - env: KITCHEN_PLATFORM=debian KITCHEN_RECIPE=source KITCHEN_VARIANT=classic
    - env: KITCHEN_PLATFORM=ubuntu KITCHEN_RECIPE=binary KITCHEN_VARIANT=core
    - env: KITCHEN_PLATFORM=ubuntu KITCHEN_RECIPE=source KITCHEN_VARIANT=core
    - env: KITCHEN_PLATFORM=ubuntu KITCHEN_RECIPE=binary KITCHEN_VARIANT=unlimited
    - env: KITCHEN_PLATFORM=ubuntu KITCHEN_RECIPE=source KITCHEN_VARIANT=unlimited
    - env: KITCHEN_PLATFORM=ubuntu KITCHEN_RECIPE=binary KITCHEN_VARIANT=classic
    - env: KITCHEN_PLATFORM=ubuntu KITCHEN_RECIPE=source KITCHEN_VARIANT=classic
    - env: KITCHEN_PLATFORM=centos KITCHEN_RECIPE=binary KITCHEN_VARIANT=core
    - env: KITCHEN_PLATFORM=centos KITCHEN_RECIPE=source KITCHEN_VARIANT=core
    - env: KITCHEN_PLATFORM=centos KITCHEN_RECIPE=binary KITCHEN_VARIANT=unlimited
    - env: KITCHEN_PLATFORM=centos KITCHEN_RECIPE=source KITCHEN_VARIANT=unlimited
    - env: KITCHEN_PLATFORM=centos KITCHEN_RECIPE=binary KITCHEN_VARIANT=classic
    - env: KITCHEN_PLATFORM=centos KITCHEN_RECIPE=package KITCHEN_VARIANT=core
    - env: KITCHEN_PLATFORM=centos KITCHEN_RECIPE=package KITCHEN_VARIANT=classic
    - env: KITCHEN_PLATFORM=centos KITCHEN_RECIPE=package KITCHEN_VARIANT=xt
  allow_failures:
    - rvm: ruby-head
script:
  - bundle exec rake
  - test -z "$KITCHEN_PLATFORM" || travis_wait 30 bundle exec rake kitchen:all
